Traceback (most recent call last):
  File "/home/hieu/src/BCRTree_release/gctree/work/da/32c6b69044e623b31950d926652325/modify_tree_colors.py", line 165, in <module>
    main(get_parser(sys.argv[1:]))
  File "/home/hieu/src/BCRTree_release/gctree/work/da/32c6b69044e623b31950d926652325/modify_tree_colors.py", line 70, in main
    idmapseqdf = pd.read_csv(args.input_idmap)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'm11_IGHV1-50*01_IGHJ3*01_39_2.aln.id_map_seq.csv'
